//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.09 at 05:11:06 PM MSK 
//


package ru.kinghp.portfolio_manager.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.kinghp.portfolio_manager.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAllPapersRequest_QNAME = new QName("http://www.ws.portfolio_manager.kinghp.ru", "getAllPapersRequest");
    private final static QName _GetAllPortfoliosRequest_QNAME = new QName("http://www.ws.portfolio_manager.kinghp.ru", "getAllPortfoliosRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.kinghp.portfolio_manager.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPaperDetailsRequest }
     * 
     */
    public GetPaperDetailsRequest createGetPaperDetailsRequest() {
        return new GetPaperDetailsRequest();
    }

    /**
     * Create an instance of {@link PostPaperUpdateRequest }
     * 
     */
    public PostPaperUpdateRequest createPostPaperUpdateRequest() {
        return new PostPaperUpdateRequest();
    }

    /**
     * Create an instance of {@link PaperDto }
     * 
     */
    public PaperDto createPaperDto() {
        return new PaperDto();
    }

    /**
     * Create an instance of {@link GetAllPapersResponse }
     * 
     */
    public GetAllPapersResponse createGetAllPapersResponse() {
        return new GetAllPapersResponse();
    }

    /**
     * Create an instance of {@link GetPaperDetailsResponse }
     * 
     */
    public GetPaperDetailsResponse createGetPaperDetailsResponse() {
        return new GetPaperDetailsResponse();
    }

    /**
     * Create an instance of {@link PostAddPaperResponse }
     * 
     */
    public PostAddPaperResponse createPostAddPaperResponse() {
        return new PostAddPaperResponse();
    }

    /**
     * Create an instance of {@link GetPortfolioDetailsRequest }
     * 
     */
    public GetPortfolioDetailsRequest createGetPortfolioDetailsRequest() {
        return new GetPortfolioDetailsRequest();
    }

    /**
     * Create an instance of {@link GetPortfolioDetailsResponse }
     * 
     */
    public GetPortfolioDetailsResponse createGetPortfolioDetailsResponse() {
        return new GetPortfolioDetailsResponse();
    }

    /**
     * Create an instance of {@link PortfolioDto }
     * 
     */
    public PortfolioDto createPortfolioDto() {
        return new PortfolioDto();
    }

    /**
     * Create an instance of {@link PortfoliosPaperDto }
     * 
     */
    public PortfoliosPaperDto createPortfoliosPaperDto() {
        return new PortfoliosPaperDto();
    }

    /**
     * Create an instance of {@link GetAllPortfoliosResponse }
     * 
     */
    public GetAllPortfoliosResponse createGetAllPortfoliosResponse() {
        return new GetAllPortfoliosResponse();
    }

    /**
     * Create an instance of {@link PostPortfolioRemovePaperRequest }
     * 
     */
    public PostPortfolioRemovePaperRequest createPostPortfolioRemovePaperRequest() {
        return new PostPortfolioRemovePaperRequest();
    }

    /**
     * Create an instance of {@link PostAddPaperRequest }
     * 
     */
    public PostAddPaperRequest createPostAddPaperRequest() {
        return new PostAddPaperRequest();
    }

    /**
     * Create an instance of {@link PostAddPortfolioRequest }
     * 
     */
    public PostAddPortfolioRequest createPostAddPortfolioRequest() {
        return new PostAddPortfolioRequest();
    }

    /**
     * Create an instance of {@link PostPortfolioRemovePaperResponse }
     * 
     */
    public PostPortfolioRemovePaperResponse createPostPortfolioRemovePaperResponse() {
        return new PostPortfolioRemovePaperResponse();
    }

    /**
     * Create an instance of {@link PostPortfolioAddPaperResponse }
     * 
     */
    public PostPortfolioAddPaperResponse createPostPortfolioAddPaperResponse() {
        return new PostPortfolioAddPaperResponse();
    }

    /**
     * Create an instance of {@link PostPortfolioAddPaperRequest }
     * 
     */
    public PostPortfolioAddPaperRequest createPostPortfolioAddPaperRequest() {
        return new PostPortfolioAddPaperRequest();
    }

    /**
     * Create an instance of {@link PostPaperUpdateResponse }
     * 
     */
    public PostPaperUpdateResponse createPostPaperUpdateResponse() {
        return new PostPaperUpdateResponse();
    }

    /**
     * Create an instance of {@link PostAddPortfolioResponse }
     * 
     */
    public PostAddPortfolioResponse createPostAddPortfolioResponse() {
        return new PostAddPortfolioResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ws.portfolio_manager.kinghp.ru", name = "getAllPapersRequest")
    public JAXBElement<Object> createGetAllPapersRequest(Object value) {
        return new JAXBElement<Object>(_GetAllPapersRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ws.portfolio_manager.kinghp.ru", name = "getAllPortfoliosRequest")
    public JAXBElement<Object> createGetAllPortfoliosRequest(Object value) {
        return new JAXBElement<Object>(_GetAllPortfoliosRequest_QNAME, Object.class, null, value);
    }

}
