//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.09 at 05:11:06 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ws.portfolio_manager.kinghp.ru", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.kinghp.portfolio_manager.ws;
