//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.09 at 05:11:06 PM MSK 
//


package ru.kinghp.portfolio_manager.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="portfolioId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="removingPaperId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "portfolioId",
    "removingPaperId"
})
@XmlRootElement(name = "postPortfolioRemovePaperRequest")
public class PostPortfolioRemovePaperRequest {

    protected long portfolioId;
    protected long removingPaperId;

    /**
     * Gets the value of the portfolioId property.
     * 
     */
    public long getPortfolioId() {
        return portfolioId;
    }

    /**
     * Sets the value of the portfolioId property.
     * 
     */
    public void setPortfolioId(long value) {
        this.portfolioId = value;
    }

    /**
     * Gets the value of the removingPaperId property.
     * 
     */
    public long getRemovingPaperId() {
        return removingPaperId;
    }

    /**
     * Sets the value of the removingPaperId property.
     * 
     */
    public void setRemovingPaperId(long value) {
        this.removingPaperId = value;
    }

}
