//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.09 at 05:11:06 PM MSK 
//


package ru.kinghp.portfolio_manager.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="portfolioDto" type="{http://www.ws.portfolio_manager.kinghp.ru}portfolioDto"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "portfolioDto"
})
@XmlRootElement(name = "postAddPortfolioRequest")
public class PostAddPortfolioRequest {

    @XmlElement(required = true)
    protected PortfolioDto portfolioDto;

    /**
     * Gets the value of the portfolioDto property.
     * 
     * @return
     *     possible object is
     *     {@link PortfolioDto }
     *     
     */
    public PortfolioDto getPortfolioDto() {
        return portfolioDto;
    }

    /**
     * Sets the value of the portfolioDto property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortfolioDto }
     *     
     */
    public void setPortfolioDto(PortfolioDto value) {
        this.portfolioDto = value;
    }

}
