spring:
  datasource:
    url: jdbc:postgresql://${db_url}/portfolio_manager
    username: ${db_user}
    password: ${db_password}
    driver-class: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      show_sql: true

  liquibase:
    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml #это путь по умолчанию, можно не указывать
    contexts: dev #на разных контекстах могут быть выполнены разные сценарии (dev, test)


fhtoken: ${fh_token}

jwt:
  sessionTime: 120000000
  secret: jwt_secret_key

server:
  error:
    include-message: always

#Для плагина maven для создания классов из xsd
project:
  basedir: D:/Java/portfolio_manager